apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: haproxy-kubernetes-ingress
    path: patch-service.yaml
  - target:
      kind: ConfigMap
      name: haproxy-kubernetes-ingress
    path: patch-configmap.yaml
  - target:
      kind: ClusterIssuer
      name: nerdd-issuer
    path: patch-issuer.yaml
