apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=np-scout
      - modelClass=np_scout.NPScoutModel
      - topic=np-scout-checkpoints
      - consumerGroup=predict-checkpoints-np-scout
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=10m
      - memRequest=1Gi
      - cpuLimit=1
      - memLimit=2Gi
