apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=gloryx
      - modelClass=gloryx.GloryXModel
      - topic=gloryx-checkpoints
      - consumerGroup=predict-checkpoints-gloryx
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=5
      - memRequest=8Gi
      - cpuLimit=10
      - memLimit=8Gi
