- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: OMP_NUM_THREADS
      value: "4"
    - name: MKL_NUM_THREADS
      value: "4"
    - name: OPENBLAS_NUM_THREADS
      value: "4"
    - name: NUMEXPR_NUM_THREADS
      value: "4"
