apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=hitdexter
      - modelClass=hitdexter.HitDexter3Model
      - topic=hitdexter3-checkpoints
      - consumerGroup=predict-checkpoints-hitdexter3
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=10m
      - memRequest=600Mi
      - cpuLimit=4000m
      - memLimit=2G
