apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-https
  annotations:
    cert-manager.io/cluster-issuer: nerdd-issuer
spec:
  ingressClassName: haproxy
  rules:
    - host: nerdd.univie.ac.at
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
  tls:
    - hosts:
        - nerdd.univie.ac.at
      secretName: argocd-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-grpc-ingress-https
  annotations:
    haproxy.org/backend-protocol: "grpc"
    cert-manager.io/cluster-issuer: nerdd-issuer
spec:
  ingressClassName: haproxy
  rules:
    - host: nerdd.univie.ac.at
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
  tls:
    - hosts:
        - nerdd.univie.ac.at
      secretName: argocd-tls
