apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rethinkdb.yaml
  - statefulset.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml
  # storage
  - blockpool.yaml
  - storageclass.yaml
