kind: Service
apiVersion: v1
metadata:
  name: rethinkdb
  labels:
    app: rethinkdb
spec:
  selector:
    app: rethinkdb
  ports:
    - name: admin
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: intracluster
      protocol: TCP
      port: 29015
      targetPort: 29015
    - name: client
      protocol: TCP
      port: 28015
      targetPort: 28015
  type: ClusterIP
