apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-internal
spec:
  clusterIP: None
  selector:
    app: rethinkdb
  ports:
    - name: driver
      port: 29015
    - name: cluster
      port: 29016
    - name: admin
      port: 8080
