apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=fame3r
      - modelClass=fame3r._nerdd.FAME3RModel
      - topic=fame3r-checkpoints
      - consumerGroup=predict-checkpoints-fame3r
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=10m
      - memRequest=100Mi
      - cpuLimit=4
      - memLimit=9Gi
