apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=glory
      - modelClass=glory.GloryModel
      - topic=glory-checkpoints
      - consumerGroup=predict-checkpoints-glory
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=4
      - memRequest=4Gi
      - cpuLimit=6
      - memLimit=7Gi
