apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=trialblazer
      - modelClass=trialblazer.Nerdd.TrialblazerModel
      - topic=trialblazer-checkpoints
      - consumerGroup=predict-checkpoints-trialblazer
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=4
      - memRequest=3Gi
      - cpuLimit=5
      - memLimit=6Gi
