apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=fame
      - modelClass=fame.Fame3Model
      - topic=fame3-checkpoints
      - consumerGroup=predict-checkpoints-fame3
      - minReplicaCount=1
      - maxReplicaCount=10
      - cpuRequest=3
      - memRequest=17G
      - cpuLimit=5
      - memLimit=17G
