apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=cyplebrity
      - modelClass=cyplebrity.CyplebrityModel
      - topic=cyplebrity-checkpoints
      - consumerGroup=predict-checkpoints-cyplebrity
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=10m
      - memRequest=50Mi
      - cpuLimit=2000m
      - memLimit=4Gi
