apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=cypstrate
      - modelClass=cypstrate.CypstrateModel
      - topic=cypstrate-checkpoints
      - consumerGroup=predict-checkpoints-cypstrate
      - minReplicaCount=3
      - maxReplicaCount=3
      - cpuRequest=10m
      - memRequest=1500Mi
      - cpuLimit=3000m
      - memLimit=5000Mi
