apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-console
  annotations:
    # https
    cert-manager.io/cluster-issuer: nerdd-issuer
    # authentication
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-secret: redpanda-auth
    haproxy.org/auth-realm: "Redpanda Console Login"
    # redpanda infers the root path from X-Forwarded-Prefix header
    haproxy.org/request-set-header: X-Forwarded-Prefix /redpanda
spec:
  ingressClassName: haproxy
  rules:
    - host: nerdd.univie.ac.at
      http:
        paths:
          - path: /redpanda
            pathType: Prefix
            backend:
              service:
                name: redpanda-console
                port:
                  number: 8080
  tls:
    - hosts:
        - nerdd.univie.ac.at
      secretName: redpanda-tls
